Repository CA-G12/Blog-app-Team8, pull requests merged in 2022-08, with the labels that each got.

#2 Create file structure
  .env.example
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/400.html
  public/500.html
  public/index.html
  public/index.js
  public/posts.html
  public/signup.html
  src/app.js
  src/controllers/index.js
  src/database/config/build.js
  src/database/config/build.sql
  src/database/config/connection.js
  src/database/config/seeder.sql
  src/database/queries/index.js
  src/index.js
  src/routes/index.js
Labels: approved, awaiting-review

#4 3 database schema
  src/database/config/build.sql
  src/database/config/seeder.sql
Labels: approved

#7 5 jwt joi
  package-lock.json
  package.json
  src/app.js
Labels: approved

#8 Created the build.js and connection.js files Relates #6
  .env.example
  src/database/config/build.js
  src/database/config/connection.js
Labels: approved

#26 create signup page html css
  public/css/styles.css
  public/signup.html
Labels: awaiting-review

#27 Sign up backend
  .vscode/settings.json
  public/css/styles.css
  public/img/undraw_thought_process_re_om58.svg
  public/signup.html
  src/controllers/index.js
  src/controllers/users/index.js
  src/controllers/users/postUser.js
  src/database/config/build.sql
  src/database/queries/index.js
  src/database/queries/users/addUser.js
  src/database/queries/users/checkUserExistance.js
  src/database/queries/users/index.js
  src/middlewares/verifyToken.js
  src/routes/index.js
Labels: approved

#28 13 create login page
  public/css/styles.css
  public/index.html
  public/index.js
  src/controllers/index.js
  src/controllers/users/index.js
  src/controllers/users/login.js
  src/database/queries/index.js
  src/database/queries/users/index.js
  src/database/queries/users/login.js
  src/routes/index.js
  src/routes/login.js
Labels: approved

#29 22 handle errors
  .vscode/settings.json
  public/index.js
  src/controllers/users/login.js
Labels: approved

#33 32 create home page
  public/css/home.css
  public/home.html
  public/js/home.js
Labels: approved

#34 Front end validation sign up
  public/css/styles.css
  public/js/validation.js
  public/signup.html
  src/controllers/users/postUser.js
  src/database/config/build.sql
  src/database/config/connection.js
  src/database/config/seeder.sql
  src/database/queries/users/addUser.js
Labels: approved

#39 handle insert request
  public/home.html
  public/js/home.js
  src/controllers/index.js
  src/controllers/posts/createPosts.js
  src/controllers/posts/index.js
  src/controllers/users/login.js
  src/database/queries/index.js
  src/database/queries/posts/createPost.js
  src/database/queries/posts/index.js
  src/routes/addPost.js
  src/routes/index.js
Labels: awating-review

#38 handle get posts
  public/home.html
  public/js/posts.js
  src/controllers/index.js
  src/controllers/posts/getPosts.js
  src/controllers/posts/index.js
  src/controllers/users/login.js
  src/database/queries/index.js
  src/database/queries/posts/addPost.js
  src/database/queries/posts/getPosts.js
  src/database/queries/posts/index.js
  src/routes/index.js
Labels: awating-review

#43 Simple edits
  .env.example
  src/controllers/users/login.js
  src/middlewares/verifyToken.js
Labels: awating-review

#45 add posts
  public/js/home.js
  src/controllers/posts/createPosts.js
  src/controllers/users/postUser.js
  src/database/queries/posts/createPost.js
Labels: approved

#46 41 create dom for profile
  public/home.html
  public/js/Dom.js
  public/js/posts.js
  public/js/profile.js
  public/posts.html
  public/profile.html
  src/controllers/posts/createPosts.js
  src/controllers/posts/getPosts.js
  src/middlewares/verifyToken.js
Labels: approved

#50 refator query and some codes
  public/js/profile.js
  src/controllers/posts/createPosts.js
  src/database/queries/posts/createPost.js
  src/database/queries/posts/getUserPosts.js
Labels: approved

#53 Handle delete post
  public/home.html
  public/js/profile.js
  src/controllers/index.js
  src/controllers/posts/deletePost.js
  src/controllers/posts/index.js
  src/database/queries/index.js
  src/database/queries/posts/deletePostById.js
  src/database/queries/posts/index.js
  src/routes/getUserPosts.js
Labels: approved

#57 Edit path to 404 file
  src/errors/index.js
Labels: awaiting-review

#58 51 add photo feature
  public/css/home.css
  public/js/Dom.js
  public/js/posts.js
  public/js/profile.js
  public/profile.html
  src/controllers/index.js
  src/controllers/posts/getPosts.js
  src/controllers/posts/index.js
  src/controllers/users/addUserImage.js
  src/controllers/users/index.js
  src/database/queries/index.js
  src/database/queries/posts/getPosts.js
  src/database/queries/posts/getUserPosts.js
  src/database/queries/users/addUserImage.js
  src/database/queries/users/index.js
  src/routes/index.js
  src/routes/userImage.js
Labels: awaiting-review
